### ISSUE TITLE
class_accuracy_metrics is not found

### ISSUE THREAD

**Issue by mrifkikurniawan** [VerwimpEli/SSLAD_Track_3#1]
On track 3A, the class_accuracy_metrics class is not found in Avalanche library. 

`
Traceback (most recent call last):
  File "classification.py", line 8, in <module>
    from avalanche.evaluation.metrics import accuracy_metrics, loss_metrics, class_accuracy_metrics
ImportError: cannot import name 'class_accuracy_metrics' from 'avalanche.evaluation.metrics'
`

**Comment by VerwimpEli** [comment]
Hi, did you clone my fork of the Avalanche library or did you get the official one? Because the Class Accuracy Metric is currently not in the main library (but it's going to be soon). 

You can find my fork [here](https://github.com/VerwimpEli/avalanche.git).

Please let me know if this doesn't fix it or there are other issues!

**Comment by mrifkikurniawan** [comment]
Oh yes, I clone from official avalanche directly. Thanks for the guidance, it seems solved now.

**Comment by VerwimpEli** [comment]
Great! Good luck.
