### ISSUE TITLE
Does the test set have to be submitted to see the score?

### ISSUE THREAD

**Issue by oahzgnaw** [VerwimpEli/SSLAD_Track_3#7]
I tested on my computer and the score of the test set is always 0. Do I need to submit it on the website to see the score of the test set? If so, what should I do if the log file record is always 0? Sorry to disturb you

**Comment by VerwimpEli** [comment]
Hi!

Yes, the test set will always give score 0 because the test solutions are not in the dataset. Simply upload the .json files as you would do with the validation data and you will see your score on the test set on codalab.

Keep in mind though that only 5 submission on the test set are allowed. 

Best,
Eli

Please reopen if there's still something that's unclear :).

**Comment by oahzgnaw** [comment]
> Hi!
> 
> Yes, the test set will always give score 0 because the test solutions are not in the dataset. Simply upload the .json files as you would do with the validation data and you will see your score on the test set on codalab.
> 
> Keep in mind though that only 5 submission on the test set are allowed.
> 
> Best,
> Eli
> 
> Please reopen if there's still something that's unclear :).



> Hi!
> 
> Yes, the test set will always give score 0 because the test solutions are not in the dataset. Simply upload the .json files as you would do with the validation data and you will see your score on the test set on codalab.
> 
> Keep in mind though that only 5 submission on the test set are allowed.
> 
> Best,
> Eli
> 
> Please reopen if there's still something that's unclear :).

Thank you for your answer. The json file of the verification set is included in the data set. Where can I find the json file of the test set?
